ignoreWorkspaceRootCheck: true

shamefullyHoist: true

shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1

packages:
  - playground
  - test/fixtures/nuxt-v3
  - test/fixtures/nuxt-v4
