ignoreWorkspaceRootCheck: true

shamefullyHoist: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1

packages:
  - test/fixtures/*

ignoredBuiltDependencies:
  - esbuild
  - vue-demi
